#!/bin/sh
#
# Run motion detection software
#

case "$1" in
  start)
     echo "Running motion ..."
     modprobe bcm2835-v4l2
     rpio_pwm
     motion
     ;;
  stop)
     echo -n "Stopping motion ..."
     kill -SIGINT $(pidof motion)
     kill -SIGINT $(pidof rpio_pwm)
     rmmod bcm2835-v4l2
     ;;
  restart|reload)
     "$0" stop
     "$0" start
     ;;
  *)
     echo "Usage: $0 {start|stop|restart}"
     exit 1
esac

exit $?


